import "../algoritmos/ejercicio1.js";
import "../algoritmos/ejercicio2.js";
import "../algoritmos/ejercicio3.js";
import "../algoritmos/ejercicio4.js";
import "../algoritmos/ejercicio5.js";
import "../algoritmos/ejercicio6.js";
import "../algoritmos/ejercicio7.js";
import "../algoritmos/ejercicio8.js";
import "../algoritmos/ejercicio9.js";
import "../algoritmos/ejercicio10.js";
import "../algoritmos/ejercicio11.js";
import "../algoritmos/ejercicio12.js";
import "../algoritmos/ejercicio13.js";
import "../algoritmos/ejercicio14.js";
import "../algoritmos/ejercicio15.js";
// import "../algoritmos/ejercicio16.js";
// import "../algoritmos/ejercicio17.js";
// import "../algoritmos/ejercicio18.js";
// import "../algoritmos/ejercicio19.js";
// import "../algoritmos/ejercicio20.js";